language: ruby

rvm:
  - 1.9.3
  - 2.1

before_script:
  - "RAILS_ENV=test bundle exec rake app:db:schema:load"

script: "bundle exec rake"

gemfile:
  - "gemfiles/rails_3_1.gemfile"
  - "gemfiles/rails_3_2.gemfile"
  - "gemfiles/rails_4_0.gemfile"
  - "gemfiles/rails_4_1.gemfile"
  - "gemfiles/rails_4_2.gemfile"
